"""new neonseq migration

Revision ID: 28237646cca3
Revises: 7e5bdc34579c
Create Date: 2025-03-03 04:16:23.489163

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28237646cca3'
down_revision = '7e5bdc34579c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('t_corrected_panchayats')
    op.drop_table('ty_corrected_panchayats')
    with op.batch_alter_table('nrega_blocks', schema=None) as batch_op:
        batch_op.alter_column('nrega_id',
               existing_type=sa.TEXT(),
               type_=sa.Integer(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('nrega_blocks', schema=None) as batch_op:
        batch_op.alter_column('nrega_id',
               existing_type=sa.Integer(),
               type_=sa.TEXT(),
               existing_nullable=False)

    op.create_table('ty_corrected_panchayats',
    sa.Column('c1', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('c2', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('c3', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('c4', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('c5', sa.TEXT(), autoincrement=False, nullable=True)
    )
    op.create_table('t_corrected_panchayats',
    sa.Column('c1', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('c2', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('c3', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('c4', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('c5', sa.TEXT(), autoincrement=False, nullable=True)
    )
    # ### end Alembic commands ###
