"""Initial neon migration

Revision ID: 555135a135d9
Revises: 
Create Date: 2025-02-26 09:04:36.508131

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '555135a135d9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('t_corrected_panchayats')
    op.drop_table('ty_corrected_panchayats')
    with op.batch_alter_table('field_data', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.alter_column('input_value',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=100),
               existing_nullable=True)
        batch_op.alter_column('completed_work_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('permissible_work_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('input_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('panchayat_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('created_on',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=20),
               existing_nullable=True)
        batch_op.create_foreign_key(None, 'nrega_completed_works', ['completed_work_id'], ['id'])
        batch_op.create_foreign_key(None, 'input_parameters', ['input_id'], ['id'])
        batch_op.create_foreign_key(None, 'nrega_panchayats', ['panchayat_id'], ['id'])
        batch_op.create_foreign_key(None, 'nrega_permissible_works', ['permissible_work_id'], ['id'])
        batch_op.create_foreign_key(None, 'users', ['created_by_id'], ['id'])

    with op.batch_alter_table('input_parameters', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=128),
               type_=sa.String(length=100),
               existing_nullable=True)
        batch_op.alter_column('label',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.String(length=80),
               existing_nullable=True)
        batch_op.alter_column('unit',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=80),
               existing_nullable=True)
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(length=1024),
               type_=sa.String(length=300),
               existing_nullable=True)
        batch_op.alter_column('element_type',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=True)
        batch_op.alter_column('constraint',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=100),
               existing_nullable=True)

    with op.batch_alter_table('inputs_and_permissibles', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.alter_column('input_parameter_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('permissible_work_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.create_foreign_key(None, 'input_parameters', ['input_parameter_id'], ['id'])
        batch_op.create_foreign_key(None, 'nrega_permissible_works', ['permissible_work_id'], ['id'])

    with op.batch_alter_table('nrega_activity_types', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.alter_column('activity_type',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=150),
               nullable=False)

    with op.batch_alter_table('nrega_beneficiary_types', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.alter_column('beneficiary_type',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=80),
               nullable=False)

    with op.batch_alter_table('nrega_blocks', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=80),
               existing_nullable=True)
        batch_op.alter_column('nrega_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('district_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.create_foreign_key(None, 'nrega_districts', ['district_id'], ['id'])

    with op.batch_alter_table('nrega_categories', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=200),
               nullable=False)
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(length=128),
               type_=sa.String(length=200),
               nullable=False)

    with op.batch_alter_table('nrega_completed_works', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.alter_column('code',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=True)
        batch_op.alter_column('name',
               existing_type=sa.TEXT(),
               type_=sa.String(length=500),
               existing_nullable=True)
        batch_op.alter_column('amount_sanctioned',
               existing_type=sa.TEXT(),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.alter_column('amount_spent',
               existing_type=sa.TEXT(),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.alter_column('person_days',
               existing_type=sa.TEXT(),
               type_=sa.Integer(),
               existing_nullable=True)
        batch_op.alter_column('start_date',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               existing_nullable=True)
        batch_op.alter_column('end_date',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               existing_nullable=True)
        batch_op.alter_column('fin_year',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=True)
        batch_op.alter_column('category_id',
               existing_type=sa.TEXT(),
               type_=sa.Integer(),
               nullable=False)
        batch_op.alter_column('panchayat_id',
               existing_type=sa.TEXT(),
               type_=sa.Integer(),
               nullable=False)
        batch_op.create_foreign_key(None, 'nrega_categories', ['category_id'], ['id'])
        batch_op.create_foreign_key(None, 'nrega_panchayats', ['panchayat_id'], ['id'])

    with op.batch_alter_table('nrega_districts', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.alter_column('name',
               existing_type=sa.TEXT(),
               type_=sa.String(length=80),
               nullable=False)
        batch_op.alter_column('nrega_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('state_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.create_unique_constraint(None, ['nrega_id'])
        batch_op.create_foreign_key(None, 'nrega_states', ['state_id'], ['id'])

    with op.batch_alter_table('nrega_major_heads', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.alter_column('major_head',
               existing_type=sa.TEXT(),
               type_=sa.String(length=150),
               nullable=False)
        batch_op.alter_column('category_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.create_foreign_key(None, 'nrega_categories', ['category_id'], ['id'])

    with op.batch_alter_table('nrega_panchayats', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.alter_column('name',
               existing_type=sa.TEXT(),
               type_=sa.String(length=80),
               nullable=False)
        batch_op.alter_column('nrega_id',
               existing_type=sa.TEXT(),
               type_=sa.BigInteger(),
               nullable=False)
        batch_op.alter_column('block_id',
               existing_type=sa.TEXT(),
               type_=sa.Integer(),
               nullable=False)
        batch_op.create_unique_constraint(None, ['nrega_id'])
        batch_op.create_foreign_key(None, 'nrega_blocks', ['block_id'], ['id'])

    with op.batch_alter_table('nrega_permissible_works', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.alter_column('permissible_work',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=False)
        batch_op.alter_column('work_type_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('major_head_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('activity_type_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('beneficiary_type_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.create_foreign_key(None, 'nrega_major_heads', ['major_head_id'], ['id'])
        batch_op.create_foreign_key(None, 'nrega_work_types', ['work_type_id'], ['id'])
        batch_op.create_foreign_key(None, 'nrega_activity_types', ['activity_type_id'], ['id'])
        batch_op.create_foreign_key(None, 'nrega_beneficiary_types', ['beneficiary_type_id'], ['id'])
        batch_op.create_foreign_key(None, 'nrega_categories', ['category_id'], ['id'])

    with op.batch_alter_table('nrega_states', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.alter_column('name',
               existing_type=sa.TEXT(),
               type_=sa.String(length=80),
               existing_nullable=True)
        batch_op.alter_column('nrega_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.create_unique_constraint(None, ['nrega_id'])

    with op.batch_alter_table('nrega_work_types', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.alter_column('work_type',
               existing_type=sa.TEXT(),
               type_=sa.String(length=200),
               nullable=False)
        batch_op.alter_column('major_head_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.create_foreign_key(None, 'nrega_major_heads', ['major_head_id'], ['id'])

    with op.batch_alter_table('plant_types', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.alter_column('name',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               nullable=False)
        batch_op.alter_column('scientific_name',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               existing_nullable=True)
        batch_op.alter_column('remarks',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               existing_nullable=True)
        batch_op.create_unique_constraint(None, ['name'])

    with op.batch_alter_table('user_feedbacks', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.alter_column('topic',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               nullable=False)
        batch_op.alter_column('feedback',
               existing_type=sa.TEXT(),
               type_=sa.String(length=500),
               nullable=False)
        batch_op.alter_column('created_on',
               existing_type=sa.TEXT(),
               type_=sa.String(length=20),
               nullable=False)
        batch_op.create_foreign_key(None, 'users', ['created_by_id'], ['id'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.alter_column('name',
               existing_type=sa.TEXT(),
               type_=sa.String(length=80),
               nullable=False)
        batch_op.alter_column('username',
               existing_type=sa.TEXT(),
               type_=sa.String(length=80),
               nullable=False)
        batch_op.alter_column('password',
               existing_type=sa.TEXT(),
               type_=sa.String(length=200),
               nullable=False)
        batch_op.alter_column('state_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.create_foreign_key(None, 'nrega_states', ['state_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('state_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('password',
               existing_type=sa.String(length=200),
               type_=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('username',
               existing_type=sa.String(length=80),
               type_=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('name',
               existing_type=sa.String(length=80),
               type_=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('user_feedbacks', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('created_on',
               existing_type=sa.String(length=20),
               type_=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('feedback',
               existing_type=sa.String(length=500),
               type_=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('topic',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('plant_types', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('remarks',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('scientific_name',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('name',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('nrega_work_types', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('major_head_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('work_type',
               existing_type=sa.String(length=200),
               type_=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('nrega_states', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('nrega_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('name',
               existing_type=sa.String(length=80),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('nrega_permissible_works', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('beneficiary_type_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('activity_type_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('major_head_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('work_type_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('permissible_work',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('nrega_panchayats', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('block_id',
               existing_type=sa.Integer(),
               type_=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('nrega_id',
               existing_type=sa.BigInteger(),
               type_=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('name',
               existing_type=sa.String(length=80),
               type_=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('nrega_major_heads', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('category_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('major_head',
               existing_type=sa.String(length=150),
               type_=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('nrega_districts', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('state_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('nrega_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('name',
               existing_type=sa.String(length=80),
               type_=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('nrega_completed_works', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('panchayat_id',
               existing_type=sa.Integer(),
               type_=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('category_id',
               existing_type=sa.Integer(),
               type_=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('fin_year',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('end_date',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('start_date',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('person_days',
               existing_type=sa.Integer(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('amount_spent',
               existing_type=sa.Float(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('amount_sanctioned',
               existing_type=sa.Float(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('name',
               existing_type=sa.String(length=500),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('code',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('nrega_categories', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=128),
               nullable=True)
        batch_op.alter_column('name',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('nrega_blocks', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('district_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('nrega_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('name',
               existing_type=sa.String(length=80),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('nrega_beneficiary_types', schema=None) as batch_op:
        batch_op.alter_column('beneficiary_type',
               existing_type=sa.String(length=80),
               type_=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('nrega_activity_types', schema=None) as batch_op:
        batch_op.alter_column('activity_type',
               existing_type=sa.String(length=150),
               type_=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('inputs_and_permissibles', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('permissible_work_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('input_parameter_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('input_parameters', schema=None) as batch_op:
        batch_op.alter_column('constraint',
               existing_type=sa.String(length=100),
               type_=sa.INTEGER(),
               existing_nullable=True)
        batch_op.alter_column('element_type',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
        batch_op.alter_column('description',
               existing_type=sa.String(length=300),
               type_=sa.VARCHAR(length=1024),
               existing_nullable=True)
        batch_op.alter_column('unit',
               existing_type=sa.String(length=80),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
        batch_op.alter_column('label',
               existing_type=sa.String(length=80),
               type_=sa.VARCHAR(length=64),
               existing_nullable=True)
        batch_op.alter_column('name',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=128),
               existing_nullable=True)
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('field_data', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('created_on',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
        batch_op.alter_column('panchayat_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('input_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('permissible_work_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('completed_work_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('input_value',
               existing_type=sa.String(length=100),
               type_=sa.INTEGER(),
               existing_nullable=True)
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    op.create_table('ty_corrected_panchayats',
    sa.Column('c1', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('c2', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('c3', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('c4', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('c5', sa.TEXT(), autoincrement=False, nullable=True)
    )
    op.create_table('t_corrected_panchayats',
    sa.Column('c1', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('c2', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('c3', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('c4', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('c5', sa.TEXT(), autoincrement=False, nullable=True)
    )
    # ### end Alembic commands ###
